### ISSUE TITLE
Task.record_action() missing 1 required positional argument: 'state'

### ISSUE THREAD

**Issue by gyardley** [agentsea/surfkit#107]
It looks like the record_action call in surf4v.py isn't returning the new 'state' argument required by the latest version of taskara - I'm repeatedly getting the error in the title, followed by a RetryError:

Error taking action: RetryError[<Future at 0x170223a40 state=finished raised TypeError>]

**Comment by pbarker** [comment]
Hey @gyardley thanks for raising this. I believe it should be fixed in https://github.com/agentsea/surfkit/pull/109/files#diff-09042ecfab81747d62ca72710e931aa289f8fb8cf4719bdd63a9dbf4e1efafa1R264 

This is now published in `0.1.238`, hopefully this helps!
