### ISSUE TITLE
create EC2 Device failed: Not authorized for images

### ISSUE THREAD

**Issue by kun432** [agentsea/surfkit#88]
seems AMI using in EC2 Device is not found or not authorized for public?

```shell
$ surfkit create device --provider ec2 -n desktop01
Creating desktop 'desktop01' using 'ec2' provider
Key pair 'desktop01' already exists. Skipping import.
(snip)
ClientError: An error occurred (AuthFailure) when calling the RunInstances operation: Not authorized for images:
[ami-06f3f5d8474ba4099]
```

```shell
 $ aws ec2 describe-images --image-ids ami-06f3f5d8474ba4099  --region us-east-1
{
    "Images": []
}
```

Notes: This might be a issue for AgentDesk.
https://github.com/agentsea/agentdesk/blob/62d53de6283a61b09063cf7a208fc3a61b2c3d24/agentdesk/vm/img.py#L20

**Comment by pbarker** [comment]
Hey @kun432 this should be fixed now, we are actively working on patching https://github.com/agentsea/surfkit/issues/87
