### ISSUE TITLE
SystemError: could not connect to desktop, is agentd running? HTTPConnectionPool(host='host.docker.internal', port=8000)

### ISSUE THREAD

**Issue by StefanDanielSchwarz** [agentsea/surfkit#92]
I'm trying to follow the Quickstart on a normal Ubuntu 22.04.4 LTS server, with Docker and qemu.

When I execute the final step, "Solve a task", I get the following error message:

```
SystemError: could not connect to desktop, is agentd running? HTTPConnectionPool(host='host.docker.internal', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7103ba9d4fd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```

On the host, a curl localhost:8000 returns the "Agent in the shell" message, indicating the endpoint is online. Whatever is producing the error message is not able to reach it, however, apparently because host.docker.internal isn't resolved properly.

System is up-to-date, including Docker. Can I make host.docker.internal resolvable, e. g. by editing the relevant container's config or hosts file, or any other ideas how I could fix this issue?

**Comment by StefanDanielSchwarz** [comment]
Success! It's now working after adding `host.docker.internal` to the host's `/etc/hosts` file, pointing it to the actual IP address, and recreating the agent container to update its hosts file.

Feel free to close this issue if you believe this fix is sufficient and the problem was isolated. However, if it's a broader issue, we should investigate further to find the root cause and a more general solution.

**Comment by pbarker** [comment]
Hey @StefanDanielSchwarz, thanks for reporting this, it should be solved in https://github.com/agentsea/surfkit/pull/96 please reopen if its still an issue for you
